baseURL: https://siddharth-gandhi.github.io/siddharth-gandhi.github.io/
languageCode: en-us
title: Siddharth Gandhi
theme: PaperMod

params:
  defaultTheme: light
  # defaultTheme: dark
  # defaultTheme: auto # to switch between dark or light according to browser theme
