# baseURL: https://siddharth-gandhi.github.io/siddharth-gandhi.github.io/
baseURL: "https://www.ssgandhi.com/"
languageCode: en-us
title: Siddharth Gandhi
# name: "Siddharth Gandhi's Personal Website"
# description: Siddharth Gandhi's Personal Website.
# profile_url: "https://ssgandhi.com"
# author: Siddharth Gandhi
theme: PaperMod

# for rendering HTML in markdown properly in the profile mode's subtitle
markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # hl_Lines: ""
    # hl_inline: false
    # lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noHl: false
    style: nord
    tabWidth: 2

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Siddharth Gandhi
  description: Siddharth Gandhi's Personal Website.
  keywords: [Blog, Portfolio, Siddharth, Gandhi, Machine Learning, Deep Learning, Natural Language Processing]
  author: Siddharth Gandhi
  DateFormat: "January 2, 2006"
  images: ["siddharth_profile.png"]
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  defaultTheme: light # auto or dark
  ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: true
  comments: false
  hideSummary: false
  VisitCount: true
  ShowWordCounts: true
  ShowLastMod: true
  UseHugoToc: true
  math: true

  # for enchanced SEO
  env: production

  assets:
    favicon: "favicon-16x16.png"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "apple-touch-icon.png"
    disableHLJS: true
    disableScrollBarStyle: true

  # label:
      # text: "Siddharth Gandhi"
      #icon: "img/Q.gif"
      # icon: "https://www.ssgandhi.com/siddharth_profile.png"
      # iconHeight: 35

  profileMode:
    enabled: true
    title: "Hello!"
    subtitle: I'm Siddharth, a Master's student at the [Language Technology Institute](https://www.lti.cs.cmu.edu/), in [Carnegie Mellon University's](https://www.cmu.edu/) [School of Computer Science](https://www.cs.cmu.edu/), studying [Intelligent Information Systems (MIIS)](https://miis.cs.cmu.edu/ ). I am passionate about building systems which can be used to augment general capabilities via seamless interactions through natural language. <br><br> My interests broadly span the intersection of deep learning (DL), information retrieval (IR) and natural language processing (NLP). Currently, I will be working with [Prof. Jamie Callan](http://www.cs.cmu.edu/~callan/) on a [neural IR](http://www.cs.cmu.edu/~callan/Projects/IIS-1815528/) project to find relevant code files to be updated in a large code base, given a new feature request/design document and using LLMs to make the required changes. <br> <br>  Previously, I graduated top of my class from VIT Vellore with a Bachelor's in Computer Science and Engineering. I was a recepient of the [DAAD WISE Scholarship](https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50015295) and worked as a Research Intern at the Technical University of Munich under [Dr. Felix Dietrich](https://fd-research.com/), where I worked on [modelling Stochastic Differential Equations using Neural Networks](https://mediatum.ub.tum.de/1686889). I further collaborated with Dr. Dietrich for my Bachelor's Thesis where we looked at [improving literature recommendations with citation-informed reranking](https://mediatum.ub.tum.de/1713430). <br><br> I'm actively looking for Summer 2024 internship in ML/DL, NLP or SDE roles. Please feel free to reach out to me via email or check out my [CV](Siddharth_Gandhi_Resume.pdf) for more details.
    imageUrl: "siddharth_profile.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: "Siddharth Gandhi Profile Image"

  socialIcons:
    - name: "email"
      url: "mailto:ssgandhi602@gmail.com"
    - name: "linkedin"
      url: "https://linkedin.com/in/ssgandhi1/"
    - name: "github"
      url: "https://github.com/siddharth-Gandhi/"
    - name: "cv"
      # url: "https://drive.google.com/file/d/1FDnTG35ZDjhGLvoxMDmvrWz8JFzk0ddQ/view?usp=sharing"
      url: "Siddharth_Gandhi_Resume.pdf"

  # homeInfoParams:
  #     Title: Hi there wave
  #     Content: Can be Info, links, about...
