# baseURL: https://siddharth-gandhi.github.io/siddharth-gandhi.github.io/
baseURL: "https://ssgandhi.com/"
languageCode: en-us
title: Siddharth Gandhi
theme: PaperMod

markup:
  goldmark:
    renderer:
      unsafe: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  defaultTheme: light # auto or dark
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hideSummary: false

  # for enchanced SEO
  env: production
  profileMode:
    enabled: true
    title: "Hello! \U0001F44B"
    subtitle: I'm Siddharth, an incoming [Master's in Intelligent Information Systems (MIIS)](https://miis.cs.cmu.edu/ ) student in Language Technology Institute at Carnegie Mellon University. <br> <br>  I recently graduated from VIT, Vellore with a Bachelor's in Computer Science and Engineering. I was a recepient of the [DAAD WISE Scholarship](https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50015295) and worked as a Research Intern at the Technical University of Munich under [Dr. Felix Dietrich](https://fd-research.com/), where I worked on [modelling Stochastic Differential Equations using Neural Networks](https://mediatum.ub.tum.de/1686889). I further continued my collaboration with Dr. Dietrich for my Bachelor's Thesis where we looked at [a better way to get Research Paper Reference Recommendations](https://mediatum.ub.tum.de/1713430). <br><br> I am passionate about Deep Learning, Multimodal Learning and Natural Language Processing and am actively looking for internship opportunities for Summer 2024.
    imageUrl: "siddharth_profile.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: "Siddharth Gandhi Profile Image"

  socialIcons:
    - name: "email"
      url: "mailto:ssgandhi602@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ssgandhi1/"
    - name: "github"
      url: "https://github.com/siddharth-Gandhi/"
    - name: "cv"
      url: "https://drive.google.com/file/d/1FDnTG35ZDjhGLvoxMDmvrWz8JFzk0ddQ/view?usp=sharing"

  # homeInfoParams:
  #     Title: Hi there wave
  #     Content: Can be Info, links, about...
