# baseURL: https://siddharth-gandhi.github.io/siddharth-gandhi.github.io/
baseURL: "https://www.ssgandhi.com/"
languageCode: en-us
title: Siddharth Gandhi
# name: "Siddharth Gandhi's Personal Website"
# description: Siddharth Gandhi's Personal Website.
# profile_url: "https://ssgandhi.com"
# author: Siddharth Gandhi
theme: PaperMod

# for rendering HTML in markdown properly in the profile mode's subtitle
markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # hl_Lines: ""
    # hl_inline: false
    # lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noHl: false
    style: nord
    tabWidth: 2

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Siddharth Gandhi
  description: Siddharth Gandhi's Personal Website.
  keywords: [Blog, Portfolio, Siddharth, Gandhi, Machine Learning, Deep Learning, Natural Language Processing]
  author: Siddharth Gandhi
  DateFormat: "January 2, 2006"
  # images: []
  showToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  defaultTheme: light # auto or dark
  ShowReadingTime: true
  # ShowShareButtons: true
  # ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: true
  comments: false
  hideSummary: false
  VisitCount: true
  ShowWordCounts: true
  ShowLastMod: true

  # for enchanced SEO
  env: production

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"
    disableHLJS: true

  # label:
      # text: "Siddharth Gandhi"
      #icon: "img/Q.gif"
      # icon: "https://www.ssgandhi.com/siddharth_profile.png"
      # iconHeight: 35

  profileMode:
    enabled: true
    title: "Hello!"
    subtitle: I'm Siddharth, an incoming Master's student at [Language Technology Institute](https://www.lti.cs.cmu.edu/), [School of Computer Science](https://www.cs.cmu.edu/), in [Carnegie Mellon University](https://www.cmu.edu/) studying [Intelligent Information Systems (MIIS)](https://miis.cs.cmu.edu/ ). I am passionate about building intelligent systems akin to JARVIS from Iron Man, which can enable seamless interactions through natural language. <br> <br>  I recently graduated from VIT, Vellore with a Bachelor's in Computer Science and Engineering. I was a recepient of the [DAAD WISE Scholarship](https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50015295) and worked as a Research Intern at the Technical University of Munich under [Dr. Felix Dietrich](https://fd-research.com/), where I worked on [modelling Stochastic Differential Equations using Neural Networks](https://mediatum.ub.tum.de/1686889). I further collaborated with Dr. Dietrich for my Bachelor's Thesis where we looked at [a better way to get Research Paper Reference Recommendations](https://mediatum.ub.tum.de/1713430). <br><br> I am actively looking for internship opportunities for Summer 2024 in Machine Learning, Deep Learning, or Natural Language Processing.
    imageUrl: "siddharth_profile.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: "Siddharth Gandhi Profile Image"

  socialIcons:
    - name: "email"
      url: "mailto:ssgandhi602@gmail.com"
    - name: "linkedin"
      url: "https://linkedin.com/in/ssgandhi1/"
    - name: "github"
      url: "https://github.com/siddharth-Gandhi/"
    - name: "cv"
      url: "https://drive.google.com/file/d/1FDnTG35ZDjhGLvoxMDmvrWz8JFzk0ddQ/view?usp=sharing"

  # homeInfoParams:
  #     Title: Hi there wave
  #     Content: Can be Info, links, about...
